# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CHaRM' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CHaRM
  pod 'Firebase/Core'
  pod ‘Firebase/Auth’

  target 'CHaRMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CHaRMUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
